### ISSUE TITLE
Multiple Bindings?

### ISSUE THREAD

**Issue by issafram** [Microsoft/vsts-rm-extensions#152]
Sorry to open an issue for this, but how does one specify multiple bindings using this extension?

**Comment by rajatagrawal-dev** [comment]
Hi @issafram 
Currently we do not support adding multiple bindings from the task. To add multiple bindings you try one of the following:
1. Since our task **adds** the binding that you specify in the task, you can add the bindings one-by-one-triggering a separate release for each binding.

2. You can also manually add the bindings in you IIS website from IIS Manager once. The IIS task will not delete the already existing bindings.

3. You can add the following command in the "**Advanced->Additional AppCmd.exe Commands**" option in the task:
_**set site /site.name:"<your_website_name>" -applicationDefaults.applicationPool:"<your_application_pool_name>" -[path='/'].[path='/'].physicalPath:"<physical_path_of_the_website>" /bindings:"http/*:8085:","https/*:443:","http/127.0.0.1:8081:"**_

Note: In solution 3, you specify your bindings as a comma separated list like this "<protocol>/<IP>:<port>:<host name>","<protocol>/<IP>:<port>:<host name>"

Warning: the last solution sets the bindings to what has been specified and removes any old bindings for the website.

**Comment by issafram** [comment]
> Since our task adds the binding that you specify in the task, you can add the bindings one-by-one-triggering a separate release for each binding.

Can I just add multiple tasks to the same release?  Like can I have one task per binding?

Also, option 3 seems very attractive.  But it might need some complicated variables to work.  I don't want to input my website name in multiple locations.  The comma seperated list of bindings should be an option in the plugin (IMO), so that it generates the AppCmd.exe command dynamically.

What are your thoughts?

**Comment by rajatagrawal-dev** [comment]
Yes, multiple tasks in single release should work as well.

You can define a variable in your release definition and use it everywhere in the task. For example you can add a variable "websiteName" with value "myWebsiteName". Then you can use that variable in the task-just use $(websiteName) instead of "myWebsiteName".

There are no current plans to add an option for multiple bindings in the task right now but we might consider adding it in the future.

**Comment by rajatagrawal-dev** [comment]
Please reopen this issue if you have further queries regarding this.
