### ISSUE TITLE
Override parameters

### ISSUE THREAD

**Issue by sivanyuta** [Microsoft/vsts-rm-extensions#67]
When using WinRm - IIS Web App Deployment task in override parameters if we pass as a value "something with \&quot;" it is converted to \&amp;quot;
I added : name="param1",value="...\&quot;data source=blah blah blah;App=EntityFramework\&quot;"

and in final web.config it looked like  "...\&amp;quot;data source=blah blah blah;App=EntityFramework\&amp;quot;"

**Comment by sivanyuta** [comment]
Is there any way to solve this issue?

**Comment by mvvsubbu** [comment]
@ambrishm,

You have handled same issue in past can you help him with solution?

**Comment by ambrishm** [comment]
The &quot; used to escape the ‘ character creates problem because & is considered as a special character in XML and is further escaped with &amp;. Best to just use ‘ character rather than escaping it with &quot;. The following substitution works fine.

name="param1",value="...'data source=blah blah blah;App=EntityFramework';"

Thanks,

Ambrish Mishra

**Comment by sivanyuta** [comment]
Thanks for help
