### ISSUE TITLE
How to set site authentication using Deploy IIS App task?

### ISSUE THREAD

**Issue by jdshkolnik** [Microsoft/vsts-rm-extensions#92]
Hi,

Is it possible to deny anonymous authentication and enable windows authentication in the same task that creates the site?

**Comment by mvvsubbu** [comment]
I am not sure I really understood your question. Right now current task takes credentials to talk to remote machine, how it is anonymous. Can you explain more what is ask?

**Comment by jdshkolnik** [comment]
I'm talking about the web site's authentication methods in IIS. I did it using an explicit appcmd in the postsync.

**Comment by mvvsubbu** [comment]
Here we wanted maintain right balance between all the options and most commonly used. For those options that everyone may not be using we have exposed appcmd additional so that they can achieve what they need like you did. We will revisit this as more and more customers are asking about this for now we keep the experience as it is.

**Comment by theZackStack** [comment]
appcmd set config "site/app" /section:windowsAuthentication /enabled:true
appcmd set config "site/app" /section:anonymousAuthentication /enabled:false
